#!/bin/bash

if [ ! -f /opt/adsb/scripts/lib-common.bash ] ; then
    echo "Missing /opt/adsb/scripts/lib-common.bash, unable to continue."
    exit 1
else
    . /opt/adsb/scripts/lib-common.bash
    . /opt/adsb/scripts/lib-install.bash
    rootcheck
    logparent
fi

# we rotate hourly to reduce the risk of overflowing /run - but we only rotate log if longer than 2000 lines
# at that point we copy the log to the on disk log directory
if [[ -f /run/adsb-feeder-image.log ]] && (( $(wc -l < /run/adsb-feeder-image.log) > 2000 )); then
    bash /opt/adsb/scripts/log2disk.sh
fi

# if this is the update check at 1:30am, do the updates if configured
currenttime=$(TZ=$(/opt/adsb/adsb-setup/config.py get tz) date '+%H:%M')
if [[ "$currenttime" > "01:20" ]] && [[ "$currenttime" < "01:40" ]]; then
    if [ "$(/opt/adsb/adsb-setup/config.py get nightly_base_update)" = True ] ; then
        log $0 "Starting nightly OS update."
        /opt/adsb/scripts/update-os.bash
        log $0 "Nightly OS update done."
    fi
    if [ "$(/opt/adsb/adsb-setup/config.py get nightly_feeder_update)" = True ] ; then
        # First check if there is even an update available.
        current_version=$(/opt/adsb/adsb-setup/config.py get base_version)
        latest_version=$(find_latest_stable_version)
        if [ "${current_version}" = "${latest_version}" ] ; then
            log $0 "No new feeder version available."
        else
            log $0 "Starting nightly feeder update from ${current_version} " \
                "to ${latest_version}."
            systemd-run -u nightly-adsb-feeder-update /opt/adsb/scripts/update-feeder.bash $latest_version
            log $0 "Nightly feeder update done."
        fi
    fi
fi
