#!/bin/bash

if [[ ! -f /opt/adsb/init-complete ]] && grep -e 'AF_IS_BASE_CONFIG_FINISHED=True' /etc/adsb/.env; then
    echo "First time adsb-system-restart: stop bootstrap"
    systemctl disable adsb-bootstrap
    systemctl stop adsb-bootstrap
    touch /opt/adsb/init-complete
fi

/opt/adsb/docker-compose-adsb up -d -t 30 --remove-orphans
