services:
  shipfeeder:
    image: ghcr.io/sdr-enthusiasts/docker-shipfeeder:latest-build-45241
    container_name: shipfeeder
    hostname: shipfeeder
    restart: unless-stopped
    environment:
      # ais-catcher general and website related parameters
      - STATION_NAME=${MLAT_SITE_NAME_SANITIZED}
      - FEEDER_LONG=${FEEDER_LONG}
      - FEEDER_LAT=${FEEDER_LAT}
      - SITESHOW=on
      - PROMETHEUS_ENABLE=on
      - REALTIME=on
      # ais-catcher receiver-related parameters
      - RTLSDR_DEVICE_SERIAL=${FEEDER_SERIAL_AIS}
      # aggregrators-related parameters
      - AISCATCHER_MQTT_URL=${FEEDER_PORTTRACKER_MQTT_URL}
      - AISCATCHER_MQTT_CLIENT_ID=${FEEDER_PORTTRACKER_MQTT_CLIENT_ID}
      - AISCATCHER_MQTT_QOS=${FEEDER_PORTTRACKER_MQTT_QOS}
      - AISCATCHER_MQTT_TOPIC=${FEEDER_PORTTRACKER_MQTT_TOPIC}
      - AISCATCHER_MQTT_MSGFORMAT=${FEEDER_PORTTRACKER_MQTT_MSGFORMAT}
    ports:
      - ${AF_AIS_CATCHER_PORT}:80
    device_cgroup_rules:
      - "c 189:* rwm"
    tmpfs:
      - /tmp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - /dev:/dev:rw
