services:
  1090uk_STAGE2NUM:
    image: ${TNUK_CONTAINER}
    healthcheck:
      disable: true
    container_name: radar1090uk_STAGE2NUM
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    environment:
      - TZ=${FEEDER_TZ_STAGE2NUM}
      - RADAR1090_KEY=${FEEDER_1090UK_API_KEY_STAGE2NUM}
      - VERBOSE=false
      - BEASTHOST=uf_STAGE2NUM
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=256M
      - /tmp:size=128M
      - /var/log:size=32M
      - /var/lib/logrotate
