services:
  adsbhub:
    container_name: adsbhub
    image: ${DOCKER_IMAGE_ADSBHUB}
    labels:
      de.navisense/part-of: adsb-feeder
    healthcheck:
      disable: true
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    environment:
      - TZ=${FEEDER_TZ}
      - SBSHOST=ultrafeeder
      - CLIENTKEY=${FEEDER_ADSBHUB_STATION_KEY}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /dev/null:/root/.wget-hsts
    tmpfs:
      - /run:exec,size=64M
      - /var/log
