services:
  airspy_adsb:
    image: ${AIRSPY_CONTAINER}
    healthcheck:
      disable: true
    container_name: airspy_adsb
    hostname: airspy_adsb
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 189:* rwm'
    ports:
      - ${FEEDER_AIRSPY_PORT:-8070}:80
    environment:
      - AIRSPY_ADSB_VERBOSE=true
      - AIRSPY_ADSB_TIMEOUT=90
      - AIRSPY_ADSB_FEC_BITS=1
      - AIRSPY_ADSB_WHITELIST_THRESHOLD=5
      - AIRSPY_ADSB_PREAMBLE_FILTER_NONCRC=8
      - AIRSPY_ADSB_CPUTIME_TARGET=60
      - AIRSPY_ADSB_PREAMBLE_FILTER_MAX=20
      - AIRSPY_ADSB_MLAT_FREQ=12
      - AIRSPY_ADSB_RF_GAIN=${FEEDER_AIRSPY_GAIN:-auto}
      - AIRSPY_ADSB_STATS=true
      - AIRSPY_ADSB_BIAS_TEE=${FEEDER_ENABLE_BIASTEE}
      - S6_KILL_GRACETIME=1000
      - AIRSPY_ADSB_SERIAL=0x${FEEDER_SERIAL_1090}
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
      - /run/adsb-feeder-airspy:/run
    tmpfs:
      - /tmp:size=128M
      - /var/log:size=32M
