services:
  piaware:
    image: ${FA_CONTAINER}
    healthcheck:
      disable: true
    container_name: piaware
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    ports:
      - ${AF_PIAWAREMAP_PORT:-8081}:8080
      - ${AF_PIAWARESTAT_PORT:-8082}:80
    environment:
      - BEASTHOST=ultrafeeder
      - UAT_RECEIVER_TYPE=${FEEDER_PIAWARE_UAT978}
      - UAT_RECEIVER_HOST=${FEEDER_UAT978_HOST}
      - MLAT_RESULTS_BEASTHOST=ultrafeeder
      - MLAT_RESULTS_BEASTPORT=31004
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - TZ=${FEEDER_TZ}
      - FEEDER_ID=${FEEDER_PIAWARE_FEEDER_ID}
      - ALLOW_MLAT=${MLAT_ENABLE}
      - S6_KILL_GRACETIME=1000
      - PIAWARE_MINIMAL=true
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /dev/null:/var/log/piaware/current
    tmpfs:
      - /run:exec,size=64M
      - /tmp:size=16M
      - /var/log:size=16M
