services:
  fr24feed:
    image: ${FR24_CONTAINER}
    healthcheck:
      disable: true
    dns_search: . # Ensures unified DNS config.
    container_name: fr24feed
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    # fr24 apparently loops over available fds so this can save CPU
    ulimits:
      nofile: 1024
    ports:
      - ${AF_FLIGHTRADAR_PORT:-8754}:8754
    environment:
      - BEASTHOST=ultrafeeder
      - FR24KEY=${FEEDER_FR24_SHARING_KEY}
      - FR24KEY_UAT=${FEEDER_FR24_UAT_SHARING_KEY}
      - MLAT=${FEEDER_FR24_MLAT:-}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log
