services:
  nanofeeder:
    image: ${ULTRAFEEDER_CONTAINER}
    healthcheck:
      disable: true
    container_name: nanofeeder
    hostname: nanofeeder
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    tty: false # work-around for /dev read-only mount + /dev/console error
    device_cgroup_rules:
      # serial devices
      - 'c 188:* rwm'
      # USB devices
      - 'c 189:* rwm'
    ports:
      - ${AF_NANO_TAR1090_PORT_ADJUSTED:-8080}:80 # to expose the web interface
      - ${AF_NANO_BEAST_PORT:-30005}:30005 # Beast output
      - ${AF_NANO_BEASTREDUCE_PORT:-30006}:30006 # Beast reduce output
    environment:
      # --------------------------------------------------
      # general parameters:
      - LOGLEVEL=error
      - TZ=${FEEDER_TZ}
      # --------------------------------------------------
      # SDR related parameters:
      - READSB_DEVICE_TYPE=${FEEDER_RTL_SDR}
      - READSB_RTLSDR_DEVICE=${FEEDER_SERIAL_1090}
      - READSB_RTLSDR_PPM=${ADSB_SDR_PPM:-}
      - READSB_ENABLE_BIASTEE=${FEEDER_ENABLE_BIASTEE}
      - READSB_AUTOGAIN_INITIAL_GAIN=40.2
      - READSB_AUTOGAIN_INITIAL_INTERVAL=60
      - READSB_GAIN=autogain
      #
      # --------------------------------------------------
      # readsb/decoder parameters:
      - READSB_LAT=${FEEDER_LAT}
      - READSB_LON=${FEEDER_LONG}
      - READSB_ALT=${FEEDER_ALT_M}
      - READSB_MODEAC=false
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      - READSB_MAX_RANGE=${FEEDER_MAX_RANGE:-300}
      # --write-state-only-on-exit only affects the heatmap/replay data and traces
      # this configuration has no traces and the heatmap/replay data are written every 30 min anyhow
      # docker stop ultrafeeder will result in proper readsb exit which writes the state anyhow
      - READSB_WRITE_STATE_ONLY_ON_EXIT=true
      #
      # get data from sdrplay / airspy_adsb / dump978
      - ULTRAFEEDER_CONFIG=${FEEDER_ULTRAFEEDER_CONFIG}
      # --------------------------------------------------
      # TAR1090 (Map Web Page) parameters:
      - UPDATE_TAR1090=false
      - TAR1090_DISABLE=false
      # reduce history for nanofeeder
      - HISTORY_SIZE=225
      - INTERVAL=15
      # disable heatmap data
      - READSB_ENABLE_HEATMAP=false
      # options for the µImage:
      - MLATHUB_DISABLE=true
      - READSB_NET_BR_OPTIMIZE_FOR_MLAT=${READSB_NET_BR_OPTIMIZE_FOR_MLAT}
      # --------------------------------------------------
      # GRAPHS1090 (Decoder and System Status Web Page) parameters:
      # The two 978 related parameters should only be included if you are running dump978 for UAT reception (USA only)
      - GRAPHS1090_DISABLE=true
      - ENABLE_978=${FEEDER_ENABLE_UAT978}
      - URL_978=${FEEDER_URL_978}
      - URL_AIRSPY=${FEEDER_URL_AIRSPY:-}
      - URL_1090_SIGNAL=${FEEDER_URL_1090_SIGNAL:-}
      - S6_KILL_GRACETIME=1000
      #
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /etc/adsb/nanofeeder/globe_history:/var/globe_history
      - /usr/local/share/osm_tiles_offline:/usr/local/share/osm_tiles_offline
      - /proc/diskstats:/proc/diskstats:ro
      - /dev:/dev:ro
      - /run/adsb-feeder-nanofeeder:/run
      - /opt/adsb/rb:${FEEDER_RB_THERMAL_HACK:-/tmp/rbt}:ro
    tmpfs:
      - /var/log:size=32M
    extra_hosts:
      - "host.docker.internal:host-gateway"
