services:
  pfclient:
    image: ${PF_CONTAINER}
    healthcheck:
      disable: true
    container_name: pfclient
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    ports:
      - ${AF_PLANEFINDER_PORT:-30053}:30053
    environment:
      - TZ=${FEEDER_TZ}
      - BEASTHOST=ultrafeeder
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - SHARECODE=${FEEDER_PLANEFINDER_SHARECODE}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log/pfclient
