services:
  pfclient:
    container_name: pfclient
    image: ${DOCKER_IMAGE_PLANEFINDER}
    labels:
      de.navisense/part-of: adsb-feeder
    healthcheck:
      disable: true
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    ports:
      - ${AF_PLANEFINDER_PORT:-30053}:30053
    environment:
      - TZ=${FEEDER_TZ}
      - BEASTHOST=ultrafeeder
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - SHARECODE=${FEEDER_PLANEFINDER_SHARECODE}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log/pfclient
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
      - "9.9.9.9"
