services:
  pfclient_STAGE2NUM:
    image: ${PF_CONTAINER}
    healthcheck:
      disable: true
    container_name: pfclient_STAGE2NUM
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    ports:
      - ${AF_PLANEFINDER_PORT_STAGE2NUM:-30053}:30053
    environment:
      - TZ=${FEEDER_TZ_STAGE2NUM}
      - BEASTHOST=uf_STAGE2NUM
      - LAT=${FEEDER_LAT_STAGE2NUM}
      - LONG=${FEEDER_LONG_STAGE2NUM}
      - SHARECODE=${FEEDER_PLANEFINDER_SHARECODE_STAGE2NUM}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log/pfclient
