services:
  planewatch_STAGE2NUM:
    image: ${PW_CONTAINER}
    healthcheck:
      disable: true
    container_name: planewatch_STAGE2NUM
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    environment:
      - GOMAXPROCS=1
      - BEASTHOST=uf_STAGE2NUM
      - LAT=${FEEDER_LAT_STAGE2NUM}
      - LONG=${FEEDER_LONG_STAGE2NUM}
      - ALT=${FEEDER_ALT_M_STAGE2NUM}m
      - TZ=${FEEDER_TZ_STAGE2NUM}
      - API_KEY=${FEEDER_PLANEWATCH_API_KEY_STAGE2NUM}
      - ENABLE_MLAT=${MLAT_ENABLE_STAGE2NUM}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log
