services:
  rbfeeder_STAGE2NUM:
    image: ${RB_CONTAINER}
    healthcheck:
      disable: true
    container_name: rbfeeder_STAGE2NUM
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    environment:
      - BEASTHOST=uf_STAGE2NUM
      - UAT_RECEIVER_HOST=${FEEDER_RB_UAT978_HOST_STAGE2NUM:-}
      - LAT=${FEEDER_LAT_STAGE2NUM}
      - LONG=${FEEDER_LONG_STAGE2NUM}
      - ALT=${FEEDER_ALT_M_STAGE2NUM}
      - TZ=${FEEDER_TZ_STAGE2NUM}
      - SHARING_KEY=${FEEDER_RADARBOX_SHARING_KEY_STAGE2NUM}
      - S6_KILL_GRACETIME=1000
      - MLAT_RESULTS_BEASTHOST=uf_STAGE2NUM
      - MLAT_RESULTS_BEASTPORT=31004
      - ENABLE_MLAT=${MLAT_ENABLE_STAGE2NUM}
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    volumes:
      - /opt/adsb/rb:${FEEDER_RB_THERMAL_HACK:-/tmp/rbt}:ro
      - /opt/adsb/rb/cpuinfo_STAGE2NUM:/proc/cpuinfo:ro
