services:
  sdrmap:
    image: ${SDRMAP_CONTAINER}
    healthcheck:
      disable: true
    container_name: sdrmap
    restart: unless-stopped
    cpu_period: 50000
    cpu_quota: 7500
    stop_grace_period: 3s
    environment:
      - BEASTHOST=ultrafeeder
      - TZ=${FEEDER_TZ}
      - LAT=${FEEDER_LAT}
      - LON=${FEEDER_LONG}
      - SMUSERNAME=${FEEDER_SM_USERNAME}
      - SMPASSWORD=${FEEDER_SM_PASSWORD}
      - ALT=${FEEDER_ALT_M}
      - MLAT=${MLAT_ENABLE}
      - MLAT_PRIVACY=${MLAT_PRIVACY}
      - SEND_SYSINFO=true
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /run/sdrmap:/run
    tmpfs:
      - /tmp:size=16M
      - /var/log:size=16M
